file_format = "0.1.1"
file_language = "en"

tags = [ "Design", "C", "image", "Programming", "logo" ]
[data] 
name = "Nisar Safi"
profile_image =  "https://i.imgur.com/4oRJU3b.png" 

user_description = """I'm a seasoned front-end developer with extensive experience working on large-scale projects within small, agile teams. Over the past five years,
I've honed my skills at an anonymous corporation, contributing to the success of various initiatives. Outside of coding, you'll often find me cheering for my favorite football team or indulging in delicious seafood delicacies." :smile:
"""



hourly_rate = 67
available = true
allow_listing = true  # Allow listing in services

[[data.website]]
text = "https://www.linkedin.com/in/nisar-safi-546a532a6?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app"
id = "lap77mv0f"

[[data.website]]
text = "https://www.upwork.com/freelancers/~015b0d3818686ae121"
id = "lap77mv0f"

[[data.website]]
text = "https://www.linkedin.com/in/nisar-safi-546a532a6?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app"
id = "lap7xv0f"

[[data.website]]
text = ""
id = "lap7xv6f"

[[data.website]]
text = "https://matrix.to/#/@fake_account:matrix.org"
id = "lap7xv5f"

[[data.website]]
text = "https://t.me/fake_account"
id = "lap7xvnf"

[[data.website]]
text = "https://www.behance.net/fake_account"
id = "ilia4uin2"

[data.addresses]

bch = "bitcoincash:qzgl22szd975lgghhd6um392g8dvkjzz7syn6mg8gz"
ltc = "LLTzfkj7iCKWc2HeQXr3ofK3Ru7Xvs8gFe"

[[services]]
category = "Programming"
sub_category = "JavaScript"
title = "Professional JavaScript development"
description = """
I can help you build your project in JavaScript language for maximum speed and efficiency

* test
* test2
* test3 

#### another title

"""
price = 80
service_image = [ "https://i.imgur.com/4oRJU3b.png" ]
id = "e49rbewvo"

[[services]]
category = "Design"
sub_category = "image"
title = "Design website for Your Business"
description = "I've experience in using Gimp to create professional images for your website and business"
price = 50
service_image = [ "https://i.imgur.com/4oRJU3b.png" ]
id = "fkuhws01b"

[[services]]
category = "Design"
sub_category = "logo"
title = "Professional logo design"
description = "I've created several logos for respected business that got approved by higher management and are being used as brand logo"
price = 60
service_image = [ "https://picsum.photos/id/163/700/400" ]
id = "893eurqly"

